In [ ]:
import tensorflow as tf
tf.constant([[1,2],[3,4]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf.zeros((3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from tensorflow.keras.datasets import mnist


The MNIST database (Modified National Institute of Standards and Technology database) is a large collection of handwritten digits. It has a training set of 60,000 examples, and a test set of 10,000 examples.
This is a dataset of 60,000 28x28 grayscale images of the 10 digits, along with a test set of 10,000 images.

MNIST images are originally 28x28 pixels. This line flattens each image into a single row of 784 (28 * 28) values.

-1 is a special value that tells the reshape function to automatically calculate the appropriate number of rows, given the desired number of columns (784 in this case).

it converts the data type of the image data to float32

This line normalizes the pixel values.

Pixel values in images usually range from 0 to 255. Dividing by 255 scales the values to a range between 0 and 1.

This normalization helps improve the performance and stability of machine learning models.

In [ ]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

x_train=x_train.reshape(-1,28*28).astype("float32")/255
x_test=x_test.reshape(-1,28*28).astype("float32")/255

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
model=keras.Sequential(
    [
        #keras.Input(shape=(28*28)),
        layers.Dense(512,input_dim= 28*28, activation="relu"),  #name is an optional parameter
        layers.Dense(256,activation="relu"),
        layers.Dense(10, activation="softmax"),

])



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(512, input_dim=28*28, activation= 'relu')) # Added input_dim
model.add(Dense(256, activation = 'relu'))
model.add(Dense(10, activation = 'softmax'))

In [ ]:
#Alternate way for Sequential API
model = keras.Sequential()
model.add(layers.Dense(512, input_dim = 28 * 28, activation="relu"))
model.add(layers.Dense(256, activation="relu", name="my_layer"))
model.add(layers.Dense(10))

In [ ]:
model.compile(
    loss=keras.losses. SparseCategoricalCrossentropy(from_logits=False), #by default logits is false so we can omit it
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)

In [ ]:
model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ 1st hidden layer (Dense)             │ (None, 512)                 │         401,920 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ 2nd hidden layer (Dense)             │ (None, 256)                 │         131,328 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ output layer (Dense)                 │ (None, 10)                  │           2,570 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 535,818 (2.04 MB)

 Trainable params: 535,818 (2.04 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=1)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 18s 9ms/step - accuracy: 0.9043 - loss: 0.3170
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.9729 - loss: 0.0829
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 17s 9ms/step - accuracy: 0.9841 - loss: 0.0507
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 20s 9ms/step - accuracy: 0.9880 - loss: 0.0372
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 21s 9ms/step - accuracy: 0.9902 - loss: 0.0304


In [ ]:
model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)

Epoch 1/5
1875/1875 - 17s - 9ms/step - accuracy: 0.9916 - loss: 0.0265
Epoch 2/5
1875/1875 - 16s - 9ms/step - accuracy: 0.9924 - loss: 0.0245
Epoch 3/5
1875/1875 - 19s - 10ms/step - accuracy: 0.9934 - loss: 0.0208
Epoch 4/5
1875/1875 - 16s - 8ms/step - accuracy: 0.9938 - loss: 0.0189
Epoch 5/5
1875/1875 - 15s - 8ms/step - accuracy: 0.9944 - loss: 0.0183


In [ ]:
model.evaluate(x_test, y_test, batch_size=32,verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9806 - loss: 0.0805


[0.0804995596408844, 0.9805999994277954]

In [ ]:
model.predict(x_test[0].reshape(1,-1))   #this will give softmax output

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


array([[2.9141804e-13, 1.3358951e-07, 1.5207358e-09, 1.4193815e-08,
        2.1260824e-13, 4.1517151e-10, 6.8650252e-14, 9.9999988e-01,
        2.5609204e-11, 1.9387848e-08]], dtype=float32)

In [ ]:
prediction=model.predict(x_test[0].reshape(1,-1))
import numpy as np
np.argmax(prediction[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step


np.int64(7)